// <auto-generated />
using DS4102Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DS4102_Exam.Migrations
{
    [DbContext(typeof(ArmyContext))]
    [Migration("20220426122836_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("DS4102Backend.Models.Mission", b =>
                {
                    b.Property<int>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MissionLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissionName")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldiersDeployed")
                        .HasColumnType("INTEGER");

                    b.HasKey("MissionId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("DS4102Backend.Models.Soldier", b =>
                {
                    b.Property<int>("SoldierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bloodtype")
                        .HasColumnType("TEXT");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnMission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoldierName")
                        .HasColumnType("TEXT");

                    b.HasKey("SoldierId");

                    b.ToTable("Soldiers");
                });

            modelBuilder.Entity("DS4102Backend.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleType")
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DS4102Backend.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InUse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponName")
                        .HasColumnType("TEXT");

                    b.HasKey("WeaponId");

                    b.ToTable("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
